# Чтобы начать работу с нужной вам конфигурацией вы должны понимать азы систем программирование и прототипирования. Для более детальной разработки нужны навыки профессионалов программирования и моделирования систем создания макетов онлайн разработки.

# Для экосистем добавленных в GitHub регулярно выходит обновление при нахождении ошибок либо багов в коде.

# Пожалуйста, не пытайтесь скопировать код, который несет за собой правообладателем на изменения основных функций. Вы всегда можете написать разработчику в комментарии для исправления любого отрезка кода.
